config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

	get 'terms_of_service', to: 'static_pages#terms_of_service'
	get 'privacy_policy', to: 'static_pages#privacy_policy'

	get 'login', to: 'user_sessions#new'
	post 'login', to: 'user_sessions#create'
	delete 'logout', to: 'user_sessions#destroy'
	
	resources :users, only: %i[new create show] do
		member do
			get :followings, :followers
		end
		resource :relationships, only: [:create, :destroy]
	end

	resources :boards do
		resources :comments, only: %i[create], shallow: true
		collection do
			get :bookmarks
			get :autocomplete
		end
	end
	resources :bookmarks, only: %i[create destroy]

	resources :posts

	resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_tags, dependent: :destroy
  has_many :tags, through: :board_tags

  validates :name, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :world, presence: true, length: { maximum: 65_535 }
  validates :charm, presence: true, length: { maximum: 65_535 }
  validates :body, presence: true, length: { maximum: 65_535 }

  scope :with_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name title world charm body]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[comments user]
  end

  def save_tags(tag_names:)
    ActiveRecord::Base.transaction do
      self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      save!
    end
    true
  rescue StandardError
    false
  end

  def tag_names
    # NOTE: pluckだと新規作成失敗時に値が残らない(返り値がnilになる)
    tags.map(&:name).join(',')
  end
end

app/models/board_tag.rb
class BoardTag < ApplicationRecord
  belongs_to :board
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :board_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :board
  validates :user_id, presence: true, uniqueness: { scope: :board_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :twitter, presence: true, length: { maximum: 255 }

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at id title twitter updated_at user_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[user]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :board_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :boards, through: :board_tags

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

	mount_uploader :avatar, AvatarUploader

	has_many :boards, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :bookmark_boards, through: :bookmarks, source: :board
	has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
	has_many :followings, through: :relationships, source: :followed
	has_many :followers, through: :reverse_of_relationships, source: :follower
	has_many :posts, dependent: :destroy

	validates :password, length: { minimum: 3}, if: -> { new_record? || chaneges[:crypted_password] },on: :create
	validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
	
	validates :email, uniqueness: true, presence: true
	validates :name, presence: true, length: { maximum: 255 }

	def own?(object)
    id == object.user_id
  end

	def bookmark(board)
		bookmark_boards << board
	end

	def unbookmark(board)
		bookmark_boards.destroy(board)
	end

	def bookmark?(board)
		bookmark_boards.include?(board)
	end

	# フォローしたときの処理
	def follow(user_id)
		relationships.create(followed_id: user_id)
	end
	# フォローを外すときの処理
	def unfollow(user_id)
		relationships.find_by(followed_id: user_id).destroy
	end
	# フォローしているか判定
	def following?(user)
		followings.include?(user)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(6)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new
    end
  end

  def edit; end

	def update
		if @post.update(post_params)
			redirect_to posts_path, success: t('defaults.message.updated', item: Post.model_name.human)
		else
			flash.now['danger'] = t('defaults.message.not_updated', item: Post.model_name.human)
			render :edit
		end
	end

	def destroy
		@post.destroy!
		redirect_to posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
	end

  private

  def find_post
		@post = current_user.posts.find(params[:id])
	end

  def post_params
    params.require(:post).permit(:title, :twitter)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top terms_of_service privacy_policy]

  def top; end

  def terms_of_service; end

  def privacy_policy; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def show
    @user = User.find(params[:id])
    @followings = @user.followings
    @followers = @user.followers
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  # フォロー一覧
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:id])
    @user = user.followers
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>推しのカルテ</h1><br>
    <h2>心を豊かにしてくれる「推し」</h2>
    <h2>そんなあなたの推しを布教しませんか？</h2>
  </div>
</div>
<div class='top'>
  <div class='container pt-3'>
    <div class='row'>
      <p class="col-12 col-md-offset-1 text-center fs-2 pt-5">推しのカルテとは</p>
      <p class="text-center">
        推しのカルテは、推しを持つ全ての皆様の<br>
        「推しを布教したい！」「同志を発見して繋がりたい！」<br>
        「グッズ情報を共有したい！」そんな気持ちを<br>
        可視化するサービスです
      </p>
      <p class="col-12 col-md-offset-1 text-center fs-2 pt-5">推しのカルテの機能</p>
      <div class="col-sm-6 pt-3">
        <div class="card">
          <h3 class="card-header text-secondary">
            <%= icon 'far', 'handshake' %>推しの布教
          </h3>
          <div class="card-body">
            <h4 class="card-title">テンプレートを使用して推しを布教！</h4>
            <p class="card-text">SNSでシェアし、推しを布教できます</p>
            <p class="card-text">まずは一覧画面でみんなの推しをチェック！</p>
            <p class="card-text">新たな推しや同志を発見できるかもしれませんよ？<p>
            <p class="card-text">「私も布教したい！」と思ったあなたユーザー登録してみませんか？<p>
            <%= link_to 'みんなの推しを見てみる', boards_path, class: "btn btn-primary mt-1" %>
          </div>
        </div>
      </div>
      <div class="col-sm-6 pt-3">
        <div class="card">
          <h3 class="card-header text-secondary">
            <%= icon 'fab', 'twitter-square' %>グッズ情報の共有
          </h3>
          <div class="card-body">
            <h4 class="card-title">Twitterを埋め込んでグッズ情報を共有しましょう</h4>
            <p class="card-text">Twitterで推しのグッズ情報を発見しても他のツイートにまぎれて探すのが大変になったりしませんか？</p>
            <p class="card-text">同志達にグッズ情報をシェアすると同時にグッズ情報を一覧で確認できます</p>
            <%= link_to 'グッズ情報を確認する', posts_path, class: "btn btn-info mt-1" %>
          </div>
          <h4 class="text-center">使い方</h4>
          <div class="text-center">
            <p>入力フォームはこんな感じ</p>
            <%= image_tag 'step1.png', size: "500x200" %>
            <p>共有したいグッズのTwitterを表示し、URLをコピー</p>
            <%= image_tag 'step2.png', size: "500x200" %>
            <p>コピーしたURLをフォームに貼り付け投稿すればTwitterを埋め込めます<p>
            <%= image_tag 'step3.png', size: "500x65" %>
          </div>
        </div>
      </div>
      <h4 class="text-center mt-5">あなたに素敵な推し活を！</h4>
      <div class="mt-3 mb-5 text-center">
        <%= link_to '推しを布教してみる', new_board_path, class: 'btn btn-success btn-lg text-white' %>
      </div>
    </div>
  </div>
</div>