config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

	get 'terms_of_service', to: 'static_pages#terms_of_service'
	get 'privacy_policy', to: 'static_pages#privacy_policy'

	get 'login', to: 'user_sessions#new'
	post 'login', to: 'user_sessions#create'
	delete 'logout', to: 'user_sessions#destroy'
	
	resources :users, only: %i[new create show] do
		member do
			get :followings, :followers
		end
		resource :relationships, only: [:create, :destroy]
	end

	resources :boards do
		resources :comments, only: %i[create], shallow: true
		collection do
			get :bookmarks
			get :autocomplete
		end
	end
	resources :bookmarks, only: %i[create destroy]

	resources :posts

	resource :profile, only: %i[show edit update]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー中", user_relationships_path(user.id), data: { turbo_method: :delete }, class: 'btn btn-success' %>
<% else %>
  <%= link_to "フォロー", user_relationships_path(user.id), data: { turbo_method: :post }, class: 'btn btn-outline-success' %>
<% end %>