config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

	get 'terms_of_service', to: 'static_pages#terms_of_service'
	get 'privacy_policy', to: 'static_pages#privacy_policy'

	get 'login', to: 'user_sessions#new'
	post 'login', to: 'user_sessions#create'
	delete 'logout', to: 'user_sessions#destroy'
	
	resources :users, only: %i[new create show] do
		member do
			get :followings, :followers
		end
		resource :relationships, only: [:create, :destroy]
	end

	resources :boards do
		resources :comments, only: %i[create], shallow: true
		collection do
			get :bookmarks
			get :autocomplete
		end
	end
	resources :bookmarks, only: %i[create destroy]

	resources :posts

	resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_tags, dependent: :destroy
  has_many :tags, through: :board_tags

  validates :name, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :world, presence: true, length: { maximum: 65_535 }
  validates :charm, presence: true, length: { maximum: 65_535 }
  validates :body, presence: true, length: { maximum: 65_535 }

  scope :with_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name title world charm body]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[comments user]
  end

  def save_tags(tag_names:)
    ActiveRecord::Base.transaction do
      self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      save!
    end
    true
  rescue StandardError
    false
  end

  def tag_names
    # NOTE: pluckだと新規作成失敗時に値が残らない(返り値がnilになる)
    tags.map(&:name).join(',')
  end
end

app/models/board_tag.rb
class BoardTag < ApplicationRecord
  belongs_to :board
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :board_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :board
  validates :user_id, presence: true, uniqueness: { scope: :board_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :twitter, presence: true, length: { maximum: 255 }

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at id title twitter updated_at user_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[user]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :board_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :boards, through: :board_tags

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

	mount_uploader :avatar, AvatarUploader

	has_many :boards, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :bookmark_boards, through: :bookmarks, source: :board
	has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
	has_many :followings, through: :relationships, source: :followed
	has_many :followers, through: :reverse_of_relationships, source: :follower
	has_many :posts, dependent: :destroy

	validates :password, length: { minimum: 3}, if: -> { new_record? || chaneges[:crypted_password] },on: :create
	validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
	
	validates :email, uniqueness: true, presence: true
	validates :name, presence: true, length: { maximum: 255 }

	def own?(object)
    id == object.user_id
  end

	def bookmark(board)
		bookmark_boards << board
	end

	def unbookmark(board)
		bookmark_boards.destroy(board)
	end

	def bookmark?(board)
		bookmark_boards.include?(board)
	end

	# フォローしたときの処理
	def follow(user_id)
		relationships.create(followed_id: user_id)
	end
	# フォローを外すときの処理
	def unfollow(user_id)
		relationships.find_by(followed_id: user_id).destroy
	end
	# フォローしているか判定
	def following?(user)
		followings.include?(user)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(6)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new
    end
  end

  def edit; end

	def update
		if @post.update(post_params)
			redirect_to posts_path, success: t('defaults.message.updated', item: Post.model_name.human)
		else
			flash.now['danger'] = t('defaults.message.not_updated', item: Post.model_name.human)
			render :edit
		end
	end

	def destroy
		@post.destroy!
		redirect_to posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
	end

  private

  def find_post
		@post = current_user.posts.find(params[:id])
	end

  def post_params
    params.require(:post).permit(:title, :twitter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def show
    @user = User.find(params[:id])
    @followings = @user.followings
    @followers = @user.followers
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  # フォロー一覧
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:id])
    @user = user.followers
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OshiKatsu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-info">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center px-5">
        <li class="nav-item">
        <%= link_to 'ログイン', login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom bg-primary'>
  <div class='container px-4 text-center'>
    <div class='row'>
      <div class="col">
        <%= link_to '利用規約', terms_of_service_path, class: "nav-link mt-2 text-secondary" %>
      </div>
      <div class="col">
        <%= link_to 'プライバシーポリシー', privacy_policy_path, class: "nav-link mt-2 text-secondary" %>
      </div>
      <div class="col">
        <%= link_to 'お問い合わせ', 'https://docs.google.com/forms/d/e/1FAIpQLSdddhZI3IVJTwtNKn0VE7TXyymxydroRirZWEt1T5nTlPFGEg/viewform', class: 'nav-link mt-2 text-secondary' %>
      </div>
      <div class="copyright">
        <p>Copyright © 2023. 推しのカルテ</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-info'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
      <ul class="navbar-nav ml-auto main-nav align-items-center px-5">
        <li class="nav-item px-2">
          <%= link_to t('posts.index.title'), posts_path, class: "nav-link mt-2 text-secondary" %>
        </li>
        <li class="nav-item px-2">
          <%= link_to t('boards.index.title'), boards_path, class: "nav-link mt-2 text-secondary" %>
        </li>
        <li class="nav-item dropdown px-2">
          <a class="nav-link dropdown-toggle mt-2 text-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user-circle"></i>マイページ
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to t('profiles.show.title'), profile_path, class: 'text-secondary px-3 dropdown-item' %>
              <%= link_to t('boards.bookmarks.title'), bookmarks_boards_path, class: 'text-secondary px-3 dropdown-item' %>
              <%= button_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item text-secondary btn btn-link' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_sidebar.html.erb
<aside class="sidebar col-lg-3 col-md-4 border-end pb-5 mt-n5" style="background:rgba(246,246,246,0.45)">
  <div class="position-sticky top-0">
    <div class="text-center pt-5">
      <h3 class="position-relative mx-auto mt-2 mt-lg-4 py-3 mb-3">
        <%= current_user.name %>
      </h3>
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to t('profiles.show.title'), profile_path %>
          <%= link_to t('boards.bookmarks.title'), bookmarks_boards_path %>
          <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </div>
</aside>